version = 0.1

[default.global.parameters]
stack_name = "daily-briefing"

[default.build.parameters]
use_container = false

[default.deploy.parameters]
capabilities       = "CAPABILITY_IAM"
confirm_changeset  = true
resolve_s3         = true
region             = "us-east-1"
profile            = "personal"
